name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'app.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo chown runner:docker /var/run/docker.sock
        name: Fix Docker permission for ACT
        if: ${{ env.ACT }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rox7/url-fetcher:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Kubernetes kubectl
        uses: azure/setup-kubectl@v1

      - name: Configure Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Update deployment image
        run: |
          kubectl rollout restart deployment url-fetcher-deployment
